# Server config
server:
  port: ${PORT:8082}

# Spring config
spring:
  application:
    name: equipment-service
  logging:
    level:
      org.springframework: WARN
      org.hibernate: WARN
  h2:
    console:
      enabled: true
      settings:
        trace: false
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  platform: h2
  datasource:
    initialization-mode: always
    data: classpath:data-h2.sql

# Eureka config
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

# Ribbon config
ribbon:
  eureka:
    enabled: true